name: asciidoctor-ghpages
author: Manoel Campos da Silva Filho
branding:
  icon: book-open
  color: blue
description: 'Build AsciiDoc GitHub Pages: recursively converts every adoc file to html, renaming resulting README.html to index.html. It also enables generating an ebook.pdf or AsciiDoctor Reveal.js slides Recursively converts every adoc file to html, renaming resulting README.html to index.html'

inputs:
  asciidoctor_params:
    description: 'Extra parameters to passs to the asciidoctor command to customize the process of building adoc files'
    required: false
  adoc_file_ext:
    description: 'The extension you are using for your AsciiDoc Files'
    default: '.adoc'
    required: false
  pdf_build:
    description: 'Defines if a PDF ebook should be built along with the html files. That will generate an ebook.pdf file inside the gh-pages branch.'
    default: 'false'
    required: false
  ebook_main_adoc_file:
    description: 'Defines the name of the main AsciiDoc file that will be used if you are generating an ebook in PDF or any other supported format. For instance, if the main ebook file is "ebook.adoc", just inform "ebook" here.'
    default: 'README'
    required: false
  slides_build:
    description: 'Defines if a slides.html file should be built using AsciiDoc Reveal.js. The slides.html file is generated inside the gh-pages branch.'
    default: 'false'
    required: false
  slides_main_adoc_file:
    description: 'Defines the name of the main AsciiDoc file that will be used if you are generating slides with Reveal.js. For instance, if the slides file is "slides.adoc", just inform "slides" here.'
    default: 'README'
    required: false
  slides_skip_asciidoctor_build:
    description: 'If slides are being generated using AsciiDoc Reveal.js, you may not want to build the regular html files using the asciidoctor command, but just using the asciidoctor-revealjs command. In order to generate only the slides.html instead of the regular html files, set this config to true.'
    default: 'false'
    required: false
                  
runs: 
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.asciidoctor_params }}
    - ${{ inputs.adoc_file_ext }}
    - ${{ inputs.slides_build }}
    - ${{ inputs.slides_main_adoc_file }}
    - ${{ inputs.slides_skip_asciidoctor_build }}
    - ${{ inputs.pdf_build }}
    - ${{ inputs.ebook_main_adoc_file }}
